const MODELS = [
  {
    id: "gpt-flagship",
    name: "OpenAI GPT Flagship",
    lab: "OpenAI",
    labColor: "#10a37f",
    icon: "⬡",
    tier: "frontier",
    description: "OpenAI's primary chat frontier models, from GPT-4 through GPT-4.1.",
    releases: [
      { version: "GPT-4", date: "2023-03-14", note: "Initial GPT-4 launch" },
      { version: "GPT-4 Turbo", date: "2023-11-06", note: "128k context, improved performance" },
      { version: "GPT-4o", date: "2024-05-13", note: "Omni model, faster and cheaper" },
      { version: "GPT-4.5", date: "2025-02-27", note: "Improved emotional intelligence" },
      { version: "GPT-4.1", date: "2025-04-14", note: "Coding-focused, 1M context" },
    ],
    notes: "GPT-5 expected. OpenAI has signaled a major model unification; cadence has accelerated significantly in 2025."
  },
  {
    id: "openai-o",
    name: "OpenAI o-series",
    lab: "OpenAI",
    labColor: "#10a37f",
    icon: "⬡",
    tier: "frontier",
    description: "OpenAI's chain-of-thought reasoning models: o1, o3, o4.",
    releases: [
      { version: "o1-preview", date: "2024-09-12", note: "First public reasoning model" },
      { version: "o1", date: "2024-12-05", note: "Full release with vision" },
      { version: "o3-mini", date: "2025-01-31", note: "Efficient reasoning model" },
      { version: "o3", date: "2025-04-16", note: "Full o3 general release" },
      { version: "o4-mini", date: "2025-04-16", note: "Latest small reasoning model" },
    ],
    notes: "o5 or successor expected. OpenAI ships reasoning models on roughly a quarterly cadence."
  },
  {
    id: "claude",
    name: "Claude",
    lab: "Anthropic",
    labColor: "#c96442",
    icon: "◆",
    tier: "frontier",
    description: "Anthropic's Claude family, known for safety research and long-context performance.",
    releases: [
      { version: "Claude 2", date: "2023-07-11", note: "Major capability leap over Claude 1" },
      { version: "Claude 2.1", date: "2023-11-21", note: "200k context, reduced hallucination" },
      { version: "Claude 3 Opus", date: "2024-03-04", note: "Claude 3 family launch, top benchmarks" },
      { version: "Claude 3.5 Sonnet", date: "2024-06-20", note: "Exceeded Opus on most evals" },
      { version: "Claude 3.5 Haiku", date: "2024-11-04", note: "Fast, affordable small model" },
      { version: "Claude 3.7 Sonnet", date: "2025-02-24", note: "Extended thinking, hybrid reasoning" },
    ],
    notes: "Claude 4 family anticipated. Anthropic has been on roughly a 3–4 month major release cycle."
  },
  {
    id: "gemini",
    name: "Google Gemini",
    lab: "Google DeepMind",
    labColor: "#4285f4",
    icon: "✦",
    tier: "frontier",
    description: "Google DeepMind's Gemini series, tightly integrated with Google Search and Workspace.",
    releases: [
      { version: "Gemini 1.0 Ultra", date: "2024-02-08", note: "First Gemini Ultra release" },
      { version: "Gemini 1.5 Pro", date: "2024-05-15", note: "1M token context window" },
      { version: "Gemini 1.5 Flash", date: "2024-05-15", note: "Lightweight, fast inference" },
      { version: "Gemini 2.0 Flash", date: "2024-12-11", note: "Multimodal, agentic capabilities" },
      { version: "Gemini 2.5 Pro", date: "2025-03-25", note: "Top coding and reasoning scores" },
      { version: "Gemini 2.5 Flash", date: "2025-05-20", note: "Google I/O 2025, efficient 2.5 variant" },
    ],
    notes: "Gemini 3 likely at Google I/O 2026. Cadence tied to Google I/O and DeepMind research cycles."
  },
  {
    id: "llama",
    name: "Llama / Maverick",
    lab: "Meta AI",
    labColor: "#0082fb",
    icon: "⬟",
    tier: "open",
    description: "Meta's open-weight Llama series, the backbone of the open-source LLM ecosystem.",
    releases: [
      { version: "Llama 2", date: "2023-07-18", note: "Open weights, commercial license" },
      { version: "Llama 3", date: "2024-04-18", note: "Significant quality jump" },
      { version: "Llama 3.1", date: "2024-07-23", note: "405B flagship, 128k context" },
      { version: "Llama 3.2", date: "2024-09-25", note: "Multimodal vision models added" },
      { version: "Llama 3.3", date: "2024-12-06", note: "70B improved instruction tuning" },
      { version: "Llama 4 Scout/Maverick", date: "2025-04-05", note: "Mixture-of-experts architecture" },
    ],
    notes: "Llama 5 in active development. Meta ships on a roughly 6-month major release cadence."
  },
  {
    id: "grok",
    name: "Grok",
    lab: "xAI",
    labColor: "#a78bfa",
    icon: "✕",
    tier: "frontier",
    description: "xAI's Grok series, trained on real-time X data with humor and directness.",
    releases: [
      { version: "Grok-1", date: "2023-11-04", note: "Initial launch on X Premium" },
      { version: "Grok-1.5", date: "2024-04-12", note: "Improved reasoning, vision" },
      { version: "Grok-2", date: "2024-08-13", note: "Flagship release with image gen" },
      { version: "Grok-3", date: "2025-02-17", note: "Claimed leading benchmark performance" },
    ],
    notes: "Grok-4 expected. xAI has been on a ~6-month cadence but accelerating with compute buildout."
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    lab: "DeepSeek AI",
    labColor: "#4d6bfe",
    icon: "◈",
    tier: "chinese",
    description: "DeepSeek's frontier models, notable for efficiency and cost-effective training.",
    releases: [
      { version: "DeepSeek-V2", date: "2024-05-06", note: "MLA attention, open weights" },
      { version: "DeepSeek-V2.5", date: "2024-09-05", note: "Combined chat and coding" },
      { version: "DeepSeek-V3", date: "2024-12-26", note: "671B MoE, trained for $6M" },
      { version: "DeepSeek-R1", date: "2025-01-20", note: "Open reasoning model, matched o1" },
      { version: "DeepSeek-V3-0324", date: "2025-03-24", note: "Updated V3 checkpoint" },
    ],
    notes: "DeepSeek-R2 and V4 expected. Extremely fast iteration cycle throughout 2024–2025."
  },
  {
    id: "qwen",
    name: "Qwen",
    lab: "Alibaba Cloud",
    labColor: "#ff6a00",
    icon: "⬢",
    tier: "chinese",
    description: "Alibaba's Qwen (Tongyi Qianwen) series, strong multilingual and coding performance.",
    releases: [
      { version: "Qwen2", date: "2024-06-06", note: "Open weights, top OSS performance" },
      { version: "Qwen2.5", date: "2024-09-19", note: "Expanded model sizes, 128k context" },
      { version: "Qwen2.5-Max", date: "2025-01-28", note: "Proprietary frontier variant" },
      { version: "QwQ-32B", date: "2025-03-05", note: "Open reasoning model" },
      { version: "Qwen3", date: "2025-04-28", note: "Hybrid thinking, 235B MoE flagship" },
    ],
    notes: "Qwen3 launched with dense and MoE variants. Next major version likely late 2025."
  },
  {
    id: "glm",
    name: "GLM",
    lab: "Zhipu AI (Z.ai)",
    labColor: "#7c3aed",
    icon: "⬣",
    tier: "chinese",
    description: "Zhipu AI's GLM series, one of China's earliest commercial large language models.",
    releases: [
      { version: "GLM-4", date: "2024-01-16", note: "Multimodal, 128k context" },
      { version: "GLM-4-Air", date: "2024-06-05", note: "Lightweight efficient variant" },
      { version: "GLM-4-Plus", date: "2024-09-05", note: "Enhanced flagship" },
      { version: "GLM-4V-Plus", date: "2025-01-20", note: "Vision-language improvements" },
    ],
    notes: "GLM-5 expected. Zhipu typically follows behind Qwen/DeepSeek on a 3–4 month cadence."
  },
  {
    id: "mistral",
    name: "Mistral",
    lab: "Mistral AI",
    labColor: "#ff7000",
    icon: "★",
    tier: "open",
    description: "Mistral AI's series of open and proprietary models, Europe's strongest LLM contender.",
    releases: [
      { version: "Mistral 7B", date: "2023-09-27", note: "Outperformed Llama 2 13B at launch" },
      { version: "Mixtral 8x7B", date: "2023-12-11", note: "Mixture-of-experts open model" },
      { version: "Mistral Large", date: "2024-02-26", note: "Proprietary frontier model" },
      { version: "Mistral Large 2", date: "2024-07-24", note: "128k context, multilingual" },
      { version: "Mistral Small 3", date: "2025-01-17", note: "24B, Apache 2.0 license" },
      { version: "Mistral Medium 3", date: "2025-05-08", note: "Cost-efficient proprietary model" },
    ],
    notes: "Mistral Large 3 expected. Tends to alternate between open-weight and proprietary releases."
  },
];
