const MODELS = [
  {
    id: "openai",
    name: "OpenAI",
    lab: "OpenAI",
    labColor: "#10a37f",
    icon: "⬡",
    tier: "frontier",
    description: "OpenAI's ChatGPT models, spanning GPT-3.5 through GPT-5.x, plus the o-series chain-of-thought reasoning models.",
    releases: [
      { version: "GPT-3.5", date: "2022-11-30", note: "First ChatGPT model; first widely public conversational LLM" },
      { version: "GPT-4", date: "2023-03-14", note: "Major multimodal leap over GPT-3.5" },
      { version: "GPT-4 Turbo", date: "2023-11-06", note: "128k context, lower cost" },
      { version: "GPT-4o", date: "2024-05-13", note: "Omni model: text, image, audio, video" },
      { version: "o1-preview + o1-mini", date: "2024-09-12", note: "First public reasoning (chain-of-thought) models" },
      { version: "o1", date: "2024-12-05", note: "Full o1 release with vision" },
      { version: "o3-mini", date: "2025-01-31", note: "Efficient small reasoning model" },
      { version: "GPT-4.5", date: "2025-02-27", note: "Large model focused on emotional intelligence; discontinued" },
      { version: "GPT-4.1", date: "2025-04-14", note: "Coding-focused, 1M token context; discontinued" },
      { version: "o3 + o4-mini", date: "2025-04-16", note: "o3 adds vision/search/Python; o4-mini is efficient reasoning" },
      { version: "GPT-5", date: "2025-08-01", note: "Network of models with fast and reasoning routing modes" },
      { version: "GPT-5.1", date: "2025-11-01", note: "Alternative personality selection" },
      { version: "GPT-5.2", date: "2025-12-01", note: "Released amid competitive pressure from Gemini 2.0" },
      { version: "GPT-5.3 Codex", date: "2026-02-01", note: "Coding-specialized variant of 5.3" },
      { version: "GPT-5.3 Instant", date: "2026-03-01", note: "Fast-answer variant of 5.3" },
      { version: "GPT-5.4", date: "2026-03-01", note: "Enterprise-focused; improved autonomous computer operation" },
      { version: "GPT-5.5", date: "2026-04-23", note: "Complex professional multi-step work; includes Cyber variant" },
      { version: "GPT-5.6 Sol / Terra / Luna", date: "2026-06-26", note: "Three-tier family: Sol (flagship reasoning), Terra (balanced), Luna (fast/low-cost); limited preview to government-approved partners" },
    ],
    notes: "OpenAI has accelerated to near-monthly releases across both GPT and o-series lines since mid-2025."
  },
  {
    id: "claude-haiku",
    name: "Claude Haiku",
    lab: "Anthropic",
    labColor: "#c96442",
    icon: "❍",
    tier: "frontier",
    description: "Anthropic's fast, affordable tier — Claude's smallest models, optimized for speed and cost over raw capability.",
    releases: [
      { version: "Claude 3 Haiku", date: "2024-03-04", note: "Part of the Claude 3 three-tier family launch" },
      { version: "Claude 3.5 Haiku", date: "2024-10-22", note: "Released alongside the updated Claude 3.5 Sonnet" },
      { version: "Claude Haiku 4.5", date: "2025-10-15", note: "Fast, affordable tier targeting smaller companies" },
    ],
    notes: "Haiku releases trail the Sonnet/Opus flagships, typically arriving as a fast-follow within the same generation."
  },
  {
    id: "claude-sonnet",
    name: "Claude Sonnet",
    lab: "Anthropic",
    labColor: "#c96442",
    icon: "❖",
    tier: "frontier",
    description: "Anthropic's mid-tier, balanced Claude models — the direct descendants of the original Claude 1/2 line, now the default choice for most coding and agentic work.",
    releases: [
      { version: "Claude 1", date: "2023-03-14", note: "First release; limited access to selected users" },
      { version: "Claude 2", date: "2023-07-11", note: "First model available to the general public" },
      { version: "Claude 2.1", date: "2023-11-21", note: "200k context window (~500 pages), reduced hallucination" },
      { version: "Claude 3 Sonnet", date: "2024-03-04", note: "Part of the Claude 3 three-tier family launch" },
      { version: "Claude 3.5 Sonnet", date: "2024-06-20", note: "Outperformed Opus on most evals; introduced Artifacts feature" },
      { version: "Claude 3.5 Sonnet (v2)", date: "2024-10-22", note: "Updated Sonnet added computer-use capability" },
      { version: "Claude 3.7 Sonnet", date: "2025-02-24", note: "Extended thinking, hybrid reasoning mode" },
      { version: "Claude Sonnet 4", date: "2025-05-22", note: "Claude 4 launch" },
      { version: "Claude Sonnet 4.5", date: "2025-09-29", note: "Continued 4.x cadence; coding and instruction following improvements" },
      { version: "Claude Sonnet 4.6", date: "2026-02-17", note: "Mid-tier 4.6 release" },
      { version: "Claude Sonnet 5", date: "2026-07-01", note: "Near-Opus quality on coding and agentic work at Sonnet cost; adaptive thinking on by default" },
    ],
    notes: "Sonnet is Anthropic's highest-cadence line, inheriting the original Claude 1/2 numbering before the tiered 3.x naming began."
  },
  {
    id: "claude-opus",
    name: "Claude Opus",
    lab: "Anthropic",
    labColor: "#c96442",
    icon: "◆",
    tier: "frontier",
    description: "Anthropic's most capable Opus-tier models, aimed at the hardest reasoning, long-horizon agentic, and knowledge-work tasks.",
    releases: [
      { version: "Claude 3 Opus", date: "2024-03-04", note: "Part of the Claude 3 three-tier family launch; topped benchmarks at release" },
      { version: "Claude Opus 4", date: "2025-05-22", note: "Claude 4 launch; rated Level 3 on safety scale" },
      { version: "Claude Opus 4.1", date: "2025-08-05", note: "Added ability to end persistently harmful conversations" },
      { version: "Claude Opus 4.5", date: "2025-11-24", note: "Infinite Chats feature addressing context limits; coding improvements" },
      { version: "Claude Opus 4.6", date: "2026-02-05", note: "Agent teams support and PowerPoint integration" },
      { version: "Claude Opus 4.7", date: "2026-04-16", note: "Users noted increased refusals vs. 4.5" },
      { version: "Claude Opus 4.8", date: "2026-05-28", note: "Latest Opus release" },
    ],
    notes: "Opus has settled into a roughly bimonthly cadence through the 4.x generation."
  },
  {
    id: "claude-fable",
    name: "Claude Fable",
    lab: "Anthropic",
    labColor: "#c96442",
    icon: "❋",
    tier: "frontier",
    description: "Anthropic's newest, most capable widely released model line, succeeding the Opus tier for the most demanding reasoning and long-horizon agentic work.",
    releases: [
      { version: "Claude Fable 5", date: "2026-06-09", note: "First 'Mythos-class' model for general users; briefly suspended June 12 for safety review, restored with promotional access" },
    ],
    notes: "Claude Fable 5 is a single-release line so far."
  },
  {
    id: "gemini",
    name: "Google Gemini",
    lab: "Google DeepMind",
    labColor: "#4285f4",
    icon: "✦",
    tier: "frontier",
    description: "Google DeepMind's Gemini series, spanning 1.0 through 3.x, tightly integrated with Google Search and Workspace.",
    releases: [
      { version: "Gemini 1.0 Pro", date: "2023-12-06", note: "Launched in Bard; Ultra/Pro/Nano three-tier family" },
      { version: "Gemini 1.0 Ultra", date: "2024-02-08", note: "Public Ultra launch via Gemini app, replacing Bard" },
      { version: "Gemini 1.5 Pro", date: "2024-02-15", note: "1M token context (~1hr video or 30k lines of code); limited preview" },
      { version: "Gemini 1.5 Flash", date: "2024-05-14", note: "Google I/O: fast, cost-efficient 1.5 variant for developers" },
      { version: "Gemini 2.0 Flash", date: "2024-12-11", note: "Native multimodal output, agentic Deep Research capability" },
      { version: "Gemini 2.0 Pro + Flash-Lite", date: "2025-02-05", note: "2.0 general availability with Pro and Flash-Lite variants" },
      { version: "Gemini 2.5 Pro", date: "2025-03-25", note: "First Gemini thinking model; chain-of-thought reasoning" },
      { version: "Gemini 2.5 Flash", date: "2025-06-01", note: "Efficient 2.5 thinking variant; Flash-Lite also released" },
      { version: "Gemini 3 Pro", date: "2025-11-18", note: "Gemini 3 launch; immediate availability across all platforms" },
      { version: "Gemini 3 Flash", date: "2025-12-01", note: "New default model, replacing Gemini 2.5 Flash" },
      { version: "Gemini 3.1 Pro", date: "2026-02-19", note: "77.1% ARC-AGI-2 score; preview release" },
    ],
    notes: "Gemini has accelerated to near-quarterly major releases. Cadence tied to Google I/O and DeepMind research cycles."
  },
  {
    id: "gemma",
    name: "Gemma",
    lab: "Google DeepMind",
    labColor: "#4285f4",
    icon: "◇",
    tier: "open",
    description: "Google DeepMind's open-weight Gemma family, from edge-sized 1B models to 31B dense and MoE variants with multimodal and specialized derivatives.",
    releases: [
      { version: "Gemma 1", date: "2024-02-21", note: "2B and 7B; source-available; 2B distilled from 7B" },
      { version: "CodeGemma", date: "2024-04-09", note: "Code-focused fine-tune; supports Python, Java, C++, and more" },
      { version: "RecurrentGemma", date: "2024-04-11", note: "Griffin-based architecture (not transformer); unlimited context" },
      { version: "Gemma 2", date: "2024-06-27", note: "2B/9B/27B; grouped-query attention; 9B distilled from 27B" },
      { version: "PaliGemma", date: "2024-07-10", note: "3B vision-language; SigLIP image encoder + Gemma 2B" },
      { version: "PaliGemma 2", date: "2024-12-04", note: "3B/10B/28B vision-language; updated to Gemma 2 backbone" },
      { version: "Gemma 3", date: "2025-03-12", note: "1B–27B; 131k context; multimodal, multilingual (140+ languages)" },
      { version: "ShieldGemma 2", date: "2025-04-01", note: "4B safety model for filtering violent and explicit imagery" },
      { version: "MedGemma", date: "2025-10-01", note: "4B and 27B medical-domain variants; not yet clinical grade" },
      { version: "Gemma 4", date: "2026-04-02", note: "E2B/E4B edge + 26B MoE + 31B Dense; Apache 2.0; 256k context on larger models" },
      { version: "Gemma 4 12B", date: "2026-06-03", note: "Unified multimodal architecture with audio support" },
    ],
    notes: "Gemma complements Gemini as Google's open-weight line. Gemma 4 switched to Apache 2.0 and added MoE architecture."
  },
  {
    id: "llama",
    name: "Llama / Muse",
    lab: "Meta AI",
    labColor: "#0082fb",
    icon: "⬟",
    tier: "open",
    description: "Meta's open-weight model family — Llama 1–4 established the open-source LLM ecosystem; succeeded by Muse Spark in 2026.",
    releases: [
      { version: "Llama 1", date: "2023-02-24", note: "Research-only weights; 6.7B–65B sizes, non-commercial" },
      { version: "Llama 2", date: "2023-07-18", note: "Commercial license; instruction-tuned chat variants included" },
      { version: "Code Llama", date: "2023-08-24", note: "Llama 2 fine-tune for coding; 7B/13B/34B sizes" },
      { version: "Llama 3", date: "2024-04-18", note: "15T token training; 8B and 70B; multimodal announced" },
      { version: "Llama 3.1", date: "2024-07-23", note: "405B flagship; 128k context; 440k petaFLOP-day training run" },
      { version: "Llama 3.2", date: "2024-09-25", note: "First multimodal Llama; 1B/3B/11B/90B sizes" },
      { version: "Llama 3.3", date: "2024-12-07", note: "70B with improved instruction tuning" },
      { version: "Llama 4 Scout + Maverick", date: "2025-04-05", note: "MoE architecture; Scout 10M context, Maverick 1M context" },
      { version: "Muse Spark", date: "2026-04-01", note: "Meta Superintelligence Labs rebranding; announced as Llama successor" },
    ],
    notes: "Meta rebranded its AI lab to Meta Superintelligence Labs in 2026. Muse Spark marks the transition away from the Llama name."
  },
  {
    id: "grok",
    name: "Grok",
    lab: "xAI",
    labColor: "#a78bfa",
    icon: "✕",
    tier: "frontier",
    description: "xAI's Grok series, trained on real-time X data; rapidly expanded from Grok-1 to the 4.x generation.",
    releases: [
      { version: "Grok-1", date: "2023-11-03", note: "Early access on X Premium+; trained in 2 months; open-sourced Mar 2024" },
      { version: "Grok-1.5", date: "2024-05-15", note: "128k context; improved reasoning (announced Mar 29)" },
      { version: "Grok-2", date: "2024-08-20", note: "Multimodal; image generation via Flux; mini variant same day" },
      { version: "Grok 3", date: "2025-02-17", note: "10× compute of Grok-2 on Colossus; Think and Big Brain modes" },
      { version: "Grok 4", date: "2025-07-09", note: "Native tool use, real-time search; SuperGrok Heavy tier" },
      { version: "Grok Code Fast 1", date: "2025-08-28", note: "Reasoning model optimized for agentic coding" },
      { version: "Grok 4.1", date: "2025-11-17", note: "Improved reasoning, multimodal, reduced hallucinations" },
      { version: "Grok 4.20 Beta", date: "2026-02-01", note: "Speed focus; agentic tool calling; low hallucination rate" },
      { version: "Grok 4.3 Beta", date: "2026-04-17", note: "Improved architecture; December 2025 knowledge cutoff" },
    ],
    notes: "xAI has accelerated to monthly releases in the 4.x era, with Fast and specialized coding variants alongside flagship models."
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    lab: "DeepSeek AI",
    labColor: "#4d6bfe",
    icon: "◈",
    tier: "chinese",
    description: "DeepSeek's frontier models, notable for efficiency and cost-effective training; V3 and R1 caused global impact in early 2025.",
    releases: [
      { version: "DeepSeek Coder", date: "2023-11-02", note: "8 code-specialized models; 16k context; source-available" },
      { version: "DeepSeek-LLM", date: "2023-11-29", note: "7B and 67B general models; trained on 2T tokens" },
      { version: "DeepSeek-V2", date: "2024-05-06", note: "236B total / 21B active; multi-head latent attention; 128k context" },
      { version: "DeepSeek-V2.5", date: "2024-09-05", note: "Merged V2-Chat and Coder-V2 into one model" },
      { version: "DeepSeek-V3", date: "2024-12-26", note: "671B MoE (37B active); full training cost ~$6M" },
      { version: "DeepSeek-R1", date: "2025-01-20", note: "Open reasoning model under MIT; matched o1 on math benchmarks" },
      { version: "DeepSeek-V3-0324", date: "2025-03-24", note: "Updated V3 checkpoint; released under MIT license" },
      { version: "DeepSeek-R1-0528", date: "2025-05-28", note: "R1 update with stricter policy adherence" },
      { version: "DeepSeek-V3.1", date: "2025-08-21", note: "Hybrid thinking/non-thinking mode; 40% improvement on key benchmarks" },
      { version: "DeepSeek-V3.2", date: "2025-12-01", note: "Sparse Attention mechanism; standard and Speciale reasoning variants" },
      { version: "DeepSeek-V4", date: "2026-04-24", note: "V4-Pro (1.6T params, 49B active) and V4-Flash (284B, 13B active); 1M context" },
    ],
    notes: "DeepSeek maintains an extremely fast iteration cycle. V4 introduced trillion-parameter scale with MoE efficiency."
  },
  {
    id: "qwen",
    name: "Qwen",
    lab: "Alibaba Cloud",
    labColor: "#ff6a00",
    icon: "⬢",
    tier: "chinese",
    description: "Alibaba's Qwen (Tongyi Qianwen) series, strong multilingual and coding performance across dense and MoE architectures.",
    releases: [
      { version: "Qwen (Tongyi Qianwen)", date: "2023-08-01", note: "Initial open weights released; public launch after regulatory approval Sept 2023" },
      { version: "Qwen2", date: "2024-06-06", note: "Open weights; top OSS performance across sizes" },
      { version: "Qwen2.5", date: "2024-09-19", note: "7 sizes (0.5B–72B); 128k context; code and math improvements" },
      { version: "QwQ-32B-Preview", date: "2024-11-01", note: "Open reasoning model under Apache 2.0; targets o1-level math/coding" },
      { version: "Qwen2.5-Max", date: "2025-01-28", note: "Proprietary frontier variant of Qwen2.5" },
      { version: "Qwen3", date: "2025-04-28", note: "Hybrid thinking; 36T token training; 119 languages; dense + MoE variants" },
      { version: "Qwen3-Max", date: "2025-09-01", note: "Proprietary 1T+ parameter flagship" },
      { version: "Qwen3.5 + Qwen3.5-Plus", date: "2026-02-01", note: "Qwen3.5 open; Plus is proprietary" },
      { version: "Qwen3.6-35B-A3B", date: "2026-04-01", note: "MoE model; 35B total / 3B active; Apache 2.0" },
    ],
    notes: "Qwen has become one of the most widely deployed open-weight families. Qwen3.x continues rapid iteration into 2026."
  },
  {
    id: "glm",
    name: "GLM",
    lab: "Zhipu AI (Z.ai)",
    labColor: "#7c3aed",
    icon: "⬣",
    tier: "chinese",
    description: "Zhipu AI's GLM series, one of China's earliest commercial large language models, now extending into the 4.x and 5.x generations.",
    releases: [
      { version: "GLM-4", date: "2024-01-16", note: "Multimodal; 128k context" },
      { version: "GLM-4-Air", date: "2024-06-05", note: "Lightweight efficient variant" },
      { version: "GLM-4-Plus", date: "2024-08-01", note: "Enhanced proprietary flagship" },
      { version: "GLM-4-Voice", date: "2024-10-01", note: "End-to-end speech model with tone and dialect adjustment" },
      { version: "GLM-4.1V-Thinking + GLM-4.5", date: "2025-07-01", note: "MIT-licensed vision-language thinking model; GLM-4.5 runs on 8× H20 chips" },
      { version: "GLM-4.5V", date: "2025-08-01", note: "106B vision model" },
      { version: "GLM-4.6", date: "2025-09-01", note: "First integration of FP8/Int4 quantization on Cambricon chips" },
      { version: "GLM-4.6V + GLM-4.7", date: "2025-12-01", note: "GLM-4.6V adds native tool-calling; GLM-4.7 targets coding tasks" },
      { version: "GLM-5", date: "2026-02-01", note: "Flagship generation leap" },
      { version: "GLM-5.1", date: "2026-04-01", note: "Open-source release; company raised API prices 10%" },
      { version: "GLM-5.2", date: "2026-06-01", note: "1M token context window" },
    ],
    notes: "Zhipu has accelerated release cadence significantly through 2025–2026, now at rough monthly intervals."
  },
  {
    id: "xiaomi",
    name: "Xiaomi MiMo",
    lab: "Xiaomi",
    labColor: "#ff6900",
    icon: "◎",
    tier: "chinese",
    description: "Xiaomi's MiMo series of open-source and frontier models, focused on agentic tasks, software engineering, and omnimodal perception.",
    releases: [
      { version: "MiMo-V2-Flash", date: "2025-12-14", note: "Open-source MoE; ranked #1 open-source on SWE-bench; 256k context" },
      { version: "MiMo-V2-Pro + V2-Omni", date: "2026-03-18", note: "Pro: 1T+ params, 1.05M context, agentic; Omni: image/video/audio, 256k context" },
      { version: "MiMo-V2.5 + V2.5-Pro", date: "2026-04-22", note: "Native omnimodal; V2.5-Pro is flagship for complex engineering; 1.05M context" },
    ],
    notes: "Xiaomi entered the frontier LLM space in late 2025 with a focus on agentic and omnimodal capabilities."
  },
  {
    id: "minimax",
    name: "MiniMax",
    lab: "MiniMax",
    labColor: "#6b4de6",
    icon: "⬙",
    tier: "chinese",
    description: "MiniMax's M-series models, spanning long-context reasoning, office productivity, roleplay, and multimodal agentic workflows.",
    releases: [
      { version: "MiniMax-01", date: "2025-01-15", note: "456B total params; 1M context; text + image understanding" },
      { version: "MiniMax M1", date: "2025-06-17", note: "Reasoning model; hybrid MoE architecture; 1M context" },
      { version: "MiniMax M2", date: "2025-10-23", note: "205K context; end-to-end coding and agentic workflows" },
      { version: "MiniMax M2.1", date: "2025-12-23", note: "10B activated params; multilingual coding; 205K context" },
      { version: "MiniMax M2-her", date: "2026-01-23", note: "Dialogue-first; optimized for roleplay and character-driven chat; 66K context" },
      { version: "MiniMax M2.5", date: "2026-02-12", note: "Office productivity (Word, Excel, PowerPoint); strong SWE benchmarks; 205K context" },
      { version: "MiniMax M2.7", date: "2026-03-18", note: "Multi-agent collaboration for complex real-world tasks; 205K context" },
      { version: "Hailuo 2.3", date: "2026-04-20", note: "Video generation; text-to-video and image-to-video" },
      { version: "MiniMax M3", date: "2026-05-31", note: "Multimodal (text/image/video input); agentic and coding focus; 1.05M context" },
    ],
    notes: "MiniMax has maintained a near-monthly cadence since late 2025, expanding from text into video generation and omnimodal capabilities."
  },
  {
    id: "nex-agi",
    name: "Nex AGI",
    lab: "Nex AGI",
    labColor: "#0ea5e9",
    icon: "◉",
    tier: "chinese",
    description: "Nex AGI's post-trained models built on open foundations, focused on agent autonomy, tool use, and real-world productivity.",
    releases: [
      { version: "Nex N1 (DeepSeek V3.1)", date: "2025-12-08", note: "Post-trained on DeepSeek V3.1; agent autonomy, tool use, coding and HTML generation; 8K context" },
      { version: "Nex N2-Pro", date: "2026-06-08", note: "MoE built on Qwen3.5; 17B active / 397B total; deep research and agentic workflows; 262K context" },
    ],
    notes: "Nex AGI specializes in post-training open-weight models for agentic use cases."
  },
  {
    id: "stepfun",
    name: "StepFun",
    lab: "StepFun",
    labColor: "#10b981",
    icon: "▲",
    tier: "chinese",
    description: "StepFun's Step series of sparse MoE models, combining multimodal perception with selectable reasoning levels for speed-cost flexibility.",
    releases: [
      { version: "Step 3.5 Flash", date: "2026-01-29", note: "Open-source sparse MoE; 196B total / 11B active per token; 262K context" },
      { version: "Step 3.7 Flash", date: "2026-05-28", note: "Multimodal with vision encoder; selectable reasoning levels; 256K context" },
    ],
    notes: "StepFun focuses on efficient sparse MoE inference with a consistent 196B/11B active parameter footprint."
  },
  {
    id: "mistral",
    name: "Mistral",
    lab: "Mistral AI",
    labColor: "#ff7000",
    icon: "★",
    tier: "open",
    description: "Mistral AI's open and proprietary models, Europe's strongest LLM contender, mixing Apache-licensed open weights with frontier proprietary releases.",
    releases: [
      { version: "Mistral 7B", date: "2023-09-27", note: "Launched via BitTorrent; outperformed Llama 2 13B; Apache 2.0" },
      { version: "Mixtral 8x7B", date: "2023-12-09", note: "Sparse MoE; 46.7B usable params; Apache 2.0; launched via Twitter link" },
      { version: "Mistral Medium", date: "2023-12-01", note: "First proprietary model; multilingual (EN/FR/ES/DE/IT)" },
      { version: "Mistral Large", date: "2024-02-26", note: "Flagship proprietary; available on Microsoft Azure" },
      { version: "Mixtral 8x22B", date: "2024-04-10", note: "141B total MoE; Apache 2.0; launched via Twitter link" },
      { version: "Codestral 22B", date: "2024-05-29", note: "Code-focused; 80+ programming languages; non-commercial license" },
      { version: "Mistral Large 2", date: "2024-07-24", note: "123B params; 128k context; Mistral Research License" },
      { version: "Mistral Small 3", date: "2025-01-17", note: "24B; Apache 2.0" },
      { version: "Mistral Small 3.1", date: "2025-03-17", note: "24B with image understanding added; Apache 2.0" },
      { version: "Mistral Medium 3", date: "2025-05-08", note: "Cost-efficient proprietary model" },
      { version: "Magistral Small + Medium", date: "2025-06-10", note: "Reasoning models with chain-of-thought; Small is Apache 2.0, Medium is proprietary" },
      { version: "Mistral Large 3 + Ministral 3", date: "2025-12-02", note: "Large 3: 675B sparse MoE (41B active), Apache 2.0; Ministral 3: 3B/8B/14B dense with vision" },
      { version: "Devstral 2", date: "2025-12-10", note: "123B code-generation specialist; modified MIT license" },
    ],
    notes: "Mistral alternates between open-weight and proprietary releases. Magistral marks their entry into the reasoning model tier."
  },
];
